# Generated by Django 5.0.6 on 2025-01-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('low-fund', 'Low Fund'), ('low-sessions', 'Low Sessions'), ('performance-alert', 'Performance Alert')], max_length=50)),
                ('content', models.TextField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
