# Generated by Django 5.1.3 on 2024-12-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='manually_activated',
            field=models.BooleanField(default=False),
        ),
    ]
