# Generated by Django 5.1.3 on 2024-12-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_session_manually_activated'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='session_type_constraint',
        ),
        migrations.AddField(
            model_name='session',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(check=models.Q(
                models.Q(('type', 'PRIVATE'), ('student__isnull', False), ('group__isnull', True)) |
                models.Q(('type', 'GROUP'), ('group__isnull', False), ('student__isnull', True))
            ), name='session_type_constraint'),
        ),
    ]
