# Generated by Django 5.0.6 on 2025-02-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_type'),
        ('students', '0003_remove_student_type'),
    ]

    operations = [
    ]
