# Generated by Django 5.0.6 on 2024-12-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_schedule_schedule_group_or_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.AddField(
            model_name='schedule',
            name='days',
            field=models.JSONField(default=list, help_text='List of weekday numbers (0-6, Monday is 0)'),
        ),
    ]
