# Generated by Django 5.1.3 on 2025-01-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_schedule_multiple_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_type',
        ),
    ]
