# Generated by Django 5.0.6 on 2025-01-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='absent', max_length=20),
        ),
    ]
