# Generated by Django 5.0.6 on 2025-01-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_group_description_group_language_group_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
